name: dank_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  device_preview: ^1.0.0

  get: ^4.6.1
  
  freezed_annotation: ^1.1.0
  retrofit: ^3.0.1
  dio: ^4.0.4
  
  intl: ^0.17.0
  url_launcher: ^6.0.18
  percent_indicator: ^4.0.0
  
  google_mobile_ads: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  build_runner:
  retrofit_generator: ^4.0.1
  freezed: ^1.1.1
  json_serializable:

flutter:

  uses-material-design: true

  assets:
    - assets/images/
  
  fonts:
  - family: NotoSans
    fonts:
      - asset: assets/fonts/NotoSans/NotoSansKR-Thin.ttf
      - asset: assets/fonts/NotoSans/NotoSansKR-Light.ttf
        weight: 300
      - asset: assets/fonts/NotoSans/NotoSansKR-Regular.ttf
        weight: 400
      - asset: assets/fonts/NotoSans/NotoSansKR-Medium.ttf
        weight: 500
      - asset: assets/fonts/NotoSans/NotoSansKR-Bold.ttf
        weight: 700
      - asset: assets/fonts/NotoSans/NotoSansKR-Black.ttf
        weight: 900

 